# Generated by Django 3.2.8 on 2021-10-25 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Api',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_id', models.IntegerField()),
                ('bot_link', models.CharField(default='http://t.me/bank_for_bot', max_length=150)),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
